version: '3.8'

services:
  xcancel:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: xcancel-bot
    restart: unless-stopped
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    labels:
      - "com.docker.compose.project=xcancel"
      - "com.docker.compose.service=xcancel"
